services:
  - type: web
    name: depth-annotation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir api app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
